### ISSUE TITLE
Builds randomly fail with parallel builds

### ISSUE THREAD

**Issue by madisp** [xvik/gradle-animalsniffer-plugin#3]
It appears that the animal sniffer plugin is picking up other task output from some other projects as failures ... perhaps there is a better way for collecting failures than relying on logger output?

**Comment by xvik** [comment]
I was trying to reproduce it, but without success so far. 

Does it mix animalsniffer errors from different modules or count some other messages as errors? 
Could you show some example of incorrect output? 
I would love to hear any other details which could help me with problem reproducing.

It would be great to collect failures in a simpler way, but animalsniffer ant task can only print errors to console and so I have to intercept them. I could use animalsniffer api directly, but It would require doing classpath/process staff manually. Not a complex task, just don't want to spend time doing possibly useless rewrite (until I know the real problem). Besides, I don't see problems with the current implementation so far: each project (in multi-project case) use it's own ant instance (inside animalsniffer task) and so listen for exact execution output.

**Comment by madisp** [comment]
sure, example incorrect output (`build/reports/animalsniffer/main.text`)

```
.Users.madis.Code.project.Note:null  there were 22 duplicate class definitions.
.Users.madis.Code.projec:null       (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
```

looks like ProGuard output intermixed with the animal sniffer one.

**Comment by xvik** [comment]
Tried with proguard task, but still can't reproduce. 
Can you please send me example project where issue could be reproduced (vyarus_at_gmai.com)?

In case if it's impossible to show your project, could you please show your gradle file (or at least parts with proguard and animalsniffer configurations and lifecycle connections between then)? 

I was tried to reproduce on 100-modules (even more but it doesn't help) project (with 3 unique modules and other mixed clones). Used proguard gradle task (not a plugin) and make it depend on build (each module performs build->proguard run) and run with up to 15 workers (--parallel --max-workers=15). Either my test module is too small and I don't have required collisions between tasks (but proguard/animalsniffer tasks collisions in different modules happen) or my tasks configuration is different (in some important aspect) and that's why I don't see the issue. Hope addition info would help.

Just in case you spot something important, here is my test config:
```groovy
           buildscript {
                repositories {
                    mavenCentral()
                }
                dependencies {
                    classpath 'net.sf.proguard:proguard-gradle:5.3.1'
                }
            }

            plugins {
                id 'ru.vyarus.animalsniffer'
            }

            subprojects {
                apply plugin: 'java'
                apply plugin: 'ru.vyarus.animalsniffer'

                animalsniffer {
                    ignoreFailures = true
                }

                repositories { mavenCentral()}
                dependencies {
                    signature 'org.codehaus.mojo.signature:java16:1.0@signature'
                    signature 'org.codehaus.mojo.signature:java15:1.0@signature'
                    signature 'org.codehaus.mojo.signature:java14:1.0@signature'
                    signature 'org.codehaus.mojo.signature:java12:1.0@signature'
                }


                jar {
                  manifest {
                    attributes 'Main-Class': "valid.Sample"
                  }
                }

                task pg(type: proguard.gradle.ProGuardTask, dependsOn: build) {
                    configuration rootProject.file('proguard.txt').absolutePath

                    ignorewarnings

                    injars "build/libs/\${project.name}.jar"
                    outjars 'build/libs/out.jar'
                }
            }
```

**Comment by xvik** [comment]
Fixed in [1.3.0](https://github.com/xvik/gradle-animalsniffer-plugin/releases/tag/1.3.0)

**Comment by to-bi** [comment]
Can we reopen this?
I am still experiencing the same problem with **version 1.4.2**:

Building a multi-module project with `org.gradle.parallel=true` fails from time to time with _Animalsniffer violations_ like this one:
`[Unrecognized error] warning: [options] bootstrap class path not set in conjunction with -source 1.7`
This is actually a warning issued by a different gradle task (`compileTestJava`) that ran in parallel to the animalsniffer task.

Not sure if this is coincidence or not: 
I noticed this problem sporadically with Gradle 4.1. After updating to Gradle 4.3.1, it occurs much more frequently.

**Comment by to-bi** [comment]
I tried some debugging: 
For some reason, the compiler warning arrives in `ReportCollector` (_from a differnt thread_) and it even contains `event.task.taskName == 'animalsniffer'`!

Here is a call stack: 
```
        at ru.vyarus.gradle.plugin.animalsniffer.report.ReportCollector.invoke(ReportCollector.groovy:66)
        at com.sun.proxy.$Proxy161.messageLogged(Unknown Source)
        at org.apache.tools.ant.Project.fireMessageLoggedEvent(Project.java:2271)
        at org.apache.tools.ant.Project.fireMessageLogged(Project.java:2370)
        at org.apache.tools.ant.Project.log(Project.java:485)
        at org.apache.tools.ant.Task.log(Task.java:294)
        at org.apache.tools.ant.Task.handleErrorOutput(Task.java:261)
        at org.apache.tools.ant.UnknownElement.handleErrorOutput(UnknownElement.java:263)
        at org.apache.tools.ant.Project.demuxOutput(Project.java:1278)
        at org.apache.tools.ant.DemuxOutputStream.processBuffer(DemuxOutputStream.java:173)
        at org.apache.tools.ant.DemuxOutputStream.write(DemuxOutputStream.java:152)
        at org.apache.tools.ant.DemuxOutputStream.write(DemuxOutputStream.java:242)
        at com.sun.tools.javac.util.Log.printRawLines(Log.java:531)
        at com.sun.tools.javac.util.Log.printLines(Log.java:497)
        at com.sun.tools.javac.main.Main.bugMessage(Main.java:587)
        at com.sun.tools.javac.main.Main.compile(Main.java:568)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:207)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:133)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
```

**Comment by xvik** [comment]
Of course, it must be reopened if you can reproduce the problem.
I will try to reproduce, but not sure it would succeed, but you implicitly suggest a great idea: to filter also by thread.. I will try this too.

**Comment by to-bi** [comment]
Great to see that this plugin is so actively maintained. Thanks!

Filter also by thread?  That's an interesting idea! I guess that could work.
Looking at [`Project.demuxOutput(...)`](https://github.com/apache/ant/blob/1.9.x/src/main/org/apache/tools/ant/Project.java#L1272), ant is also dispatching the output stream based on threads. (The problem at hand seems to be the fallback in [`Project.getThreadTask(...)`](https://github.com/apache/ant/blob/1.9.x/src/main/org/apache/tools/ant/Project.java#L2400) ): if there is no ant `task` associated with the current thread, it searches for a task with the same `threadGroup`... )

**Comment by xvik** [comment]
1.4.3 [released](https://github.com/xvik/gradle-animalsniffer-plugin/releases/tag/1.4.3)

I was able to reproduce the problem. This version should finally fix it.

**Comment by to-bi** [comment]
Thanks a lot!
It's working great ...
